name:                photon
dependencies:
- base >= 4.7 && < 5
- parsec
- bytestring
- containers
- vector
- mtl

library:
  source-dirs: src

executables:
  photon-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - photon
