name:                bf
version:             0.1.0.0
github:              "githubuser/bf"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

description:         Please see the README on GitHub at <https://github.com/githubuser/bf#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- bytestring
- mtl

library:
  source-dirs: src

executables:
  bf-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bf
