name:                sussylang

dependencies:
- base >= 4.7 && < 5
- parsec
- vector
- mtl
- bytestring

library:
  source-dirs: src

executables:
  sussylang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sussylang
