name:                deadsimple
version:             0.1.0.0
github:              "githubuser/deadsimple"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - mtl

executables:
  deadsimple-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - deadsimple
    - mtl
