name:                deadsimple

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - mtl

executables:
  deadsimple-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - deadsimple
    - mtl
